import { createStaticStyles, cssVar } from 'antd-style';

/**
 * Admin design tokens (ux-redesign-spec §1). Three groups:
 *
 * ① `ADMIN_SPACE` / `ADMIN_CONTROL_HEIGHT` — semantic numeric scales (pure JS,
 *    importable from TSX for inline sizing and from tests for assertions).
 * ② `adminColorRoles` — the only sanctioned color/shadow vocabulary: every
 *    Admin style must reference colors through these roles instead of hard
 *    coding hex/rgb literals (spec §1.2 red line). Each role maps to an antd 6
 *    token via `cssVar` (the generated `var(--ant-*)` reference is the
 *    allowed path; raw `var(--ant-*)` strings in page css are not).
 * ③ `adminDesignStyles` — reusable css fragments (card surface, page header
 *    hierarchy, focus ring, numeric type) shared by layout/sidebar/templates.
 */

/** ① 4pt spacing scale (spec §1.2: gaps collapse onto 8/12/16/24/32). */
export const ADMIN_SPACE = {
  lg: 16,
  md: 12,
  sm: 8,
  xl: 24,
  xs: 4,
  xxl: 32,
} as const;

/** Control heights for Admin toolbar / filter rows. */
export const ADMIN_CONTROL_HEIGHT = {
  lg: 40,
  md: 34,
  sm: 28,
} as const;

/**
 * ② Role → antd token map. Values are `cssVar` references (css variables
 * generated by antd-style from the active theme), so light/dark follow antd.
 */
export const adminColorRoles = {
  /** Card background surface (antd colorBgContainer). */
  cardBg: cssVar.colorBgContainer,
  /** Card corner radius (antd borderRadiusLG). */
  cardRadius: cssVar.borderRadiusLG,
  /** Layered card shadow for carded surfaces replacing pure border lines. */
  cardShadow: '0 1px 2px rgb(0 0 0 / 3%)',
  /** Input control radius (antd borderRadius). */
  controlRadius: cssVar.borderRadius,
  /** Hairline divider between groups (antd colorSplit). */
  divider: cssVar.colorSplit,
  /** Default line color (antd colorBorderSecondary). */
  border: cssVar.colorBorderSecondary,
  /** Page / content background (antd colorBgLayout). */
  pageBg: cssVar.colorBgLayout,
  /** Selected item background (antd colorPrimaryBg). */
  selectedBg: cssVar.colorPrimaryBg,
  /** Chip radius (antd borderRadiusSM). */
  chipRadius: cssVar.borderRadiusSM,
  /** Hover / zebra subtle fill (antd colorFillQuaternary). */
  subtleBg: cssVar.colorFillQuaternary,
  /** Top shadow for sticky bottom action bars. */
  stickyTopShadow: '0 -4px 16px rgb(0 0 0 / 6%)',
  /** Bottom shadow for sticky toolbars. */
  stickyBottomShadow: '0 4px 16px rgb(0 0 0 / 6%)',
  /** Primary text (antd colorText). */
  textPrimary: cssVar.colorText,
  /** Secondary text (antd colorTextSecondary). */
  textSecondary: cssVar.colorTextSecondary,
  /** Tertiary text (antd colorTextTertiary). */
  textTertiary: cssVar.colorTextTertiary,
} as const;

/**
 * ② Data-driven chart palette (spec §1.2 red line note): the plan bar colors
 * from the stats page live here as data constants (not css), each commented
 * with the antd semantic color it mirrors. B2 will re-point the stats page.
 */
export const adminChartPalette = {
  /** mirrors antd colorTextTertiary (#999) — neutral fallback */
  neutral: '#999',
  /** mirrors antd blue-6 (#1677ff, cssVar.colorPrimary equivalent) */
  primary: '#1677ff',
  /** mirrors antd gold-6 (#faad14) */
  gold: '#faad14',
  /** mirrors antd cyan-6 (#13c2c2) */
  cyan: '#13c2c2',
  /** mirrors antd purple-6 (#722ed1) */
  purple: '#722ed1',
} as const;

/**
 * ③ Reusable css fragments. Composed by adminPageStyles / sidebarStyles /
 * overview styles so the header hierarchy and numeric type stay identical
 * across the shell.
 */
export const adminDesignStyles = createStaticStyles(({ css, cssVar }) => ({
  /** Card surface: bg + border + radius + padding + soft shadow. */
  cardSurface: css`
    box-sizing: border-box;
    padding: 16px;
    border: 1px solid ${adminColorRoles.border};
    border-radius: ${adminColorRoles.cardRadius};

    background: ${adminColorRoles.cardBg};
    box-shadow: ${adminColorRoles.cardShadow};
  `,
  /** Page title level (h1): heading3 / 32px line, heading4 below 640px. */
  pageTitle: css`
    margin: 0;

    font-size: ${cssVar.fontSizeHeading3};
    font-weight: ${cssVar.fontWeightStrong};
    line-height: 32px;
    color: ${cssVar.colorText};
    letter-spacing: 0;

    @media (width < 640px) {
      font-size: ${cssVar.fontSizeHeading4};
      line-height: 28px;
    }
  `,
  /** Section title level (h2): fontSizeLG / 600 / 24px line. */
  sectionTitle: css`
    margin: 0;

    font-size: ${cssVar.fontSizeLG};
    font-weight: ${cssVar.fontWeightStrong};
    line-height: 24px;
    color: ${cssVar.colorText};
  `,
  /** Caption/eyebrow level: uppercase small caps in tertiary text. */
  caption: css`
    font-size: ${cssVar.fontSizeSM};
    font-weight: ${cssVar.fontWeightStrong};
    line-height: ${cssVar.lineHeightSM};
    color: ${cssVar.colorTextTertiary};
    letter-spacing: 0.08em;
  `,
  /** Keyboard focus ring shared by custom interactive elements. */
  focusRing: css`
    &:focus-visible {
      outline: 2px solid ${cssVar.colorPrimary};
      outline-offset: 1px;
    }
  `,
  /** Numeric type: code-family monospace for metric values (spec §1.2). */
  numericText: css`
    font-family: ${cssVar.fontFamilyCode};
    font-size: ${cssVar.fontSizeXL};
    font-weight: ${cssVar.fontWeightStrong};
    line-height: 28px;
    color: ${adminColorRoles.textPrimary};
  `,
}));

export type AdminColorRoles = typeof adminColorRoles;
