import { APP_SETTING_KEYS, type AppSettingKey } from '@/const/appSettingsRegistry';

const assign = (adapter: string, keys: AppSettingKey[]) =>
  keys.map((key) => [key, adapter] as const);

export const EXPECTED_NORMALIZER_ADAPTER_BY_KEY = Object.fromEntries([
  ...assign('about-links', [APP_SETTING_KEYS.aboutLinks]),
  ...assign('about-page', [APP_SETTING_KEYS.aboutPage]),
  ...assign('brand-home-messenger-boolean', [APP_SETTING_KEYS.homeMessengerEnabled]),
  ...assign('brand-string', [
    APP_SETTING_KEYS.aboutLogoUrl,
    APP_SETTING_KEYS.brandAuthTitle,
    APP_SETTING_KEYS.brandCopyrightText,
    APP_SETTING_KEYS.brandFaviconUrl,
    APP_SETTING_KEYS.brandLoadingSvgUrl,
    APP_SETTING_KEYS.brandLoadingText,
    APP_SETTING_KEYS.brandLogoUrl,
    APP_SETTING_KEYS.brandName,
    APP_SETTING_KEYS.brandPrimaryColor,
    APP_SETTING_KEYS.brandSlogan,
    APP_SETTING_KEYS.homeMessengerBannerTitle,
    APP_SETTING_KEYS.sidebarGenerationLabel,
    APP_SETTING_KEYS.sidebarMemberLabel,
    APP_SETTING_KEYS.sidebarMemberUrl,
  ]),
  ...assign('composio-auth-config-json-string', [APP_SETTING_KEYS.composioAuthConfigIds]),
  ...assign('composio-boolean', [APP_SETTING_KEYS.composioEnabled]),
  ...assign('composio-string', [APP_SETTING_KEYS.composioApiKey]),
  ...assign('cron-audit-retention-integer', [APP_SETTING_KEYS.cronAuditRetentionDays]),
  ...assign('cron-pending-order-expiry-integer', [APP_SETTING_KEYS.cronPendingOrderExpiryDays]),
  ...assign('cron-secret-string', [APP_SETTING_KEYS.cronSecret]),
  ...assign('desktop-login-string', [
    APP_SETTING_KEYS.desktopLoginCloudButtonLabel,
    APP_SETTING_KEYS.desktopLoginDescription,
    APP_SETTING_KEYS.desktopLoginFooterText,
    APP_SETTING_KEYS.desktopLoginLogoUrl,
    APP_SETTING_KEYS.desktopLoginTitle,
    APP_SETTING_KEYS.desktopLoginWindowTitle,
  ]),
  ...assign('desktop-update-boolean', [APP_SETTING_KEYS.desktopUpdateAutoCheck]),
  ...assign('desktop-update-channel-enum', [APP_SETTING_KEYS.desktopUpdateChannel]),
  ...assign('desktop-update-interval-integer', [APP_SETTING_KEYS.desktopUpdateCheckInterval]),
  ...assign('desktop-update-string', [
    APP_SETTING_KEYS.desktopDownloadLabel,
    APP_SETTING_KEYS.desktopDownloadUrl,
    APP_SETTING_KEYS.desktopOssAccessKeyId,
    APP_SETTING_KEYS.desktopOssAccessKeySecret,
    APP_SETTING_KEYS.desktopOssBucket,
    APP_SETTING_KEYS.desktopOssEndpoint,
    APP_SETTING_KEYS.desktopOssPath,
    APP_SETTING_KEYS.desktopUpdateCurrentVersion,
    APP_SETTING_KEYS.desktopUpdateReleaseNotes,
    APP_SETTING_KEYS.desktopUpdateServerUrl,
  ]),
  ...assign('expert-plaza-boolean', [APP_SETTING_KEYS.expertPlazaEnabled]),
  ...assign('expert-plaza-cards', [APP_SETTING_KEYS.expertPlazaCards]),
  ...assign('expert-plaza-categories', [APP_SETTING_KEYS.expertPlazaCategories]),
  ...assign('expert-plaza-string', [
    APP_SETTING_KEYS.expertPlazaDescription,
    APP_SETTING_KEYS.expertPlazaName,
  ]),
  ...assign('growth-boolean', [
    APP_SETTING_KEYS.authSignupEnabled,
    APP_SETTING_KEYS.authSignupPhoneEnabled,
    APP_SETTING_KEYS.onboardingInitialCreditsEnabled,
  ]),
  ...assign('growth-nonnegative-integer', [
    APP_SETTING_KEYS.onboardingInitialCredits,
    APP_SETTING_KEYS.uploadMaxActualSizeMb,
    APP_SETTING_KEYS.uploadMaxInputSizeMb,
  ]),
  ...assign('growth-string', [APP_SETTING_KEYS.authSignupDisabledMessage]),
  ...assign('help-menu', [APP_SETTING_KEYS.helpMenuItems]),
  ...assign('memory-trigger-mode', [APP_SETTING_KEYS.memoryUserMemoryTriggerMode]),
  ...assign('mobile-config', [APP_SETTING_KEYS.mobileConfig]),
  ...assign('mobile-config-publication', [APP_SETTING_KEYS.mobileConfigPublication]),
  ...assign('model-policy-boolean', [
    APP_SETTING_KEYS.modelPolicyApplyToEmbeddings,
    APP_SETTING_KEYS.modelPolicyApplyToGenerateObject,
    APP_SETTING_KEYS.modelPolicyEnabled,
  ]),
  ...assign('model-policy-mode-enum', [APP_SETTING_KEYS.modelPolicyMode]),
  ...assign('model-policy-string', [
    APP_SETTING_KEYS.modelPolicyDefaultModelFallback,
    APP_SETTING_KEYS.modelPolicyDeniedMessage,
  ]),
  ...assign('model-policy-string-list', [
    APP_SETTING_KEYS.modelPolicyAllowlist,
    APP_SETTING_KEYS.modelPolicyBlocklist,
  ]),
  ...assign('module-app-runtime-boolean', [
    APP_SETTING_KEYS.moduleAppExecutionEnabled,
    APP_SETTING_KEYS.moduleAppPublicExecutionEnabled,
    APP_SETTING_KEYS.moduleAppRuntimeInvocationEnabled,
    APP_SETTING_KEYS.moduleAppScheduleDispatchEnabled,
    APP_SETTING_KEYS.moduleAppWorkflowPrivilegedExecutorsEnabled,
  ]),
  ...assign('module-app-runtime-internal-url', [APP_SETTING_KEYS.moduleAppRuntimeInternalUrl]),
  ...assign('module-app-runtime-public-origin', [APP_SETTING_KEYS.moduleAppRuntimePublicOrigin]),
  ...assign('module-app-runtime-secret', [APP_SETTING_KEYS.moduleAppRuntimeInternalToken]),
  ...assign('notification-boolean', [
    APP_SETTING_KEYS.notificationDesktopEnabled,
    APP_SETTING_KEYS.notificationEmailEnabled,
    APP_SETTING_KEYS.notificationInboxEnabled,
    APP_SETTING_KEYS.notificationPushEnabled,
    APP_SETTING_KEYS.notificationSystemEnabled,
  ]),
  ...assign('notification-event-defaults-record', [APP_SETTING_KEYS.notificationEventDefaults]),
  ...assign('notification-retention-integer', [APP_SETTING_KEYS.notificationRetentionDays]),
  ...assign('notification-string', [
    APP_SETTING_KEYS.notificationSystemActionLabel,
    APP_SETTING_KEYS.notificationSystemActionUrl,
    APP_SETTING_KEYS.notificationSystemContent,
    APP_SETTING_KEYS.notificationSystemTitle,
  ]),
  ...assign('notification-type-enum', [APP_SETTING_KEYS.notificationSystemType]),
  ...assign('operations-boolean', [
    APP_SETTING_KEYS.communityCreatorRewardBannerEnabled,
    APP_SETTING_KEYS.communityFeaturedAssistantsEnabled,
    APP_SETTING_KEYS.communityFeaturedMcpsEnabled,
    APP_SETTING_KEYS.communityFeaturedSkillsEnabled,
    APP_SETTING_KEYS.communityHomeAnnouncementEnabled,
  ]),
  ...assign('operations-page-size-integer', [
    APP_SETTING_KEYS.communityFeaturedAssistantPageSize,
    APP_SETTING_KEYS.communityFeaturedMcpPageSize,
    APP_SETTING_KEYS.communityFeaturedSkillPageSize,
  ]),
  ...assign('operations-string', [
    APP_SETTING_KEYS.communityFeaturedAssistantTitle,
    APP_SETTING_KEYS.communityFeaturedMcpTitle,
    APP_SETTING_KEYS.communityFeaturedSkillCategory,
    APP_SETTING_KEYS.communityFeaturedSkillSort,
    APP_SETTING_KEYS.communityFeaturedSkillTitle,
    APP_SETTING_KEYS.communityForkAndChatLabel,
    APP_SETTING_KEYS.communityHomeAnnouncementContent,
    APP_SETTING_KEYS.communityHomeAnnouncementTitle,
    APP_SETTING_KEYS.communityHomeAnnouncementType,
    APP_SETTING_KEYS.communitySkillUseButtonLabel,
  ]),
  ...assign('orders-boolean', [APP_SETTING_KEYS.ordersManagementEnabled]),
  ...assign('payment-boolean', [
    APP_SETTING_KEYS.paymentAlipayEnabled,
    APP_SETTING_KEYS.paymentEnabled,
    APP_SETTING_KEYS.paymentModuleAppEnabled,
    APP_SETTING_KEYS.paymentSubscriptionEnabled,
    APP_SETTING_KEYS.paymentTopUpEnabled,
    APP_SETTING_KEYS.paymentWechatEnabled,
    APP_SETTING_KEYS.paymentZpayAlipayEnabled,
    APP_SETTING_KEYS.paymentZpayEnabled,
    APP_SETTING_KEYS.paymentZpayWechatEnabled,
  ]),
  ...assign('payment-cert-mode-enum', [APP_SETTING_KEYS.paymentAlipayCertMode]),
  ...assign('payment-mode-enum', [APP_SETTING_KEYS.paymentAlipayMode]),
  ...assign('payment-provider-enum', [APP_SETTING_KEYS.paymentDefaultProvider]),
  ...assign('payment-secret-string', [
    APP_SETTING_KEYS.paymentAlipayCertificate,
    APP_SETTING_KEYS.paymentAlipayMerchantPrivateKey,
    APP_SETTING_KEYS.paymentAlipayPublicKey,
    APP_SETTING_KEYS.paymentWechatApiV3Key,
    APP_SETTING_KEYS.paymentWechatMerchantPrivateKey,
    APP_SETTING_KEYS.paymentWechatPlatformCertificate,
    APP_SETTING_KEYS.paymentZpayMerchantKey,
  ]),
  ...assign('payment-string', [
    APP_SETTING_KEYS.paymentAlipayAppCertSn,
    APP_SETTING_KEYS.paymentAlipayAppId,
    APP_SETTING_KEYS.paymentAlipayRootCertSn,
    APP_SETTING_KEYS.paymentAlipaySellerId,
    APP_SETTING_KEYS.paymentWechatAppId,
    APP_SETTING_KEYS.paymentWechatMchId,
    APP_SETTING_KEYS.paymentWechatMerchantSerialNo,
    APP_SETTING_KEYS.paymentWechatPlatformCertificateSerialNo,
    APP_SETTING_KEYS.paymentZpayMerchantId,
  ]),
  ...assign('payment-url', [
    APP_SETTING_KEYS.paymentAlipayGateway,
    APP_SETTING_KEYS.paymentPublicBaseUrl,
    APP_SETTING_KEYS.paymentWechatApiBaseUrl,
    APP_SETTING_KEYS.paymentZpayApiBaseUrl,
  ]),
  ...assign('plans-faq-record-list', [APP_SETTING_KEYS.plansFaqItems]),
  ...assign('ppt-api-key', [APP_SETTING_KEYS.docmeePptApiKey]),
  ...assign('ppt-base-url', [APP_SETTING_KEYS.docmeePptBaseUrl]),
  ...assign('ppt-boolean', [
    APP_SETTING_KEYS.docmeePptAllowPdfExport,
    APP_SETTING_KEYS.docmeePptAllowPptxDownload,
    APP_SETTING_KEYS.docmeePptAuditEnabled,
    APP_SETTING_KEYS.docmeePptEnabled,
  ]),
  ...assign('ppt-creator-version-enum', [APP_SETTING_KEYS.docmeePptCreatorVersion]),
  ...assign('ppt-daily-limit', [APP_SETTING_KEYS.docmeePptDailyLimit]),
  ...assign('ppt-default-language', [APP_SETTING_KEYS.docmeePptDefaultLang]),
  ...assign('ppt-theme-color', [APP_SETTING_KEYS.docmeePptThemeColor]),
  ...assign('ppt-token-ttl-integer', [APP_SETTING_KEYS.docmeePptTokenTtlMinutes]),
  ...assign('pricing-model-rules-array', [APP_SETTING_KEYS.pricingModelRules]),
  ...assign('pricing-positive-number', [APP_SETTING_KEYS.pricingCreditMultiplier]),
  ...assign('profile-avatar-presets', [APP_SETTING_KEYS.profileAvatarPresets]),
  ...assign('profile-interest-areas', [APP_SETTING_KEYS.profileInterestAreas]),
  ...assign('recommendation-boolean', [
    APP_SETTING_KEYS.recommendationAssistantsEnabled,
    APP_SETTING_KEYS.recommendationGeneralSkillsEnabled,
    APP_SETTING_KEYS.recommendationHotSkillsEnabled,
    APP_SETTING_KEYS.recommendationMcpsEnabled,
    APP_SETTING_KEYS.recommendationSectionEnabled,
    APP_SETTING_KEYS.recommendationSkillsEnabled,
  ]),
  ...assign('recommendation-hot-sort', [APP_SETTING_KEYS.recommendationHotSkillSort]),
  ...assign('recommendation-string-list', [
    APP_SETTING_KEYS.recommendationAssistantTags,
    APP_SETTING_KEYS.recommendationGeneralSkillCategories,
    APP_SETTING_KEYS.recommendationMcpCategories,
    APP_SETTING_KEYS.recommendationSelectedTags,
    APP_SETTING_KEYS.recommendationSkillCategories,
  ]),
  ...assign('recommendation-title-string', [
    APP_SETTING_KEYS.recommendationAssistantTitle,
    APP_SETTING_KEYS.recommendationGeneralSkillTitle,
    APP_SETTING_KEYS.recommendationHotSkillTitle,
    APP_SETTING_KEYS.recommendationMcpTitle,
    APP_SETTING_KEYS.recommendationSkillTitle,
  ]),
  ...assign('referral-reward-integer', [APP_SETTING_KEYS.referralRewardCredits]),
  ...assign('runtime-model-string', [
    APP_SETTING_KEYS.defaultAgentAvatar,
    APP_SETTING_KEYS.defaultAgentModel,
    APP_SETTING_KEYS.defaultAgentName,
    APP_SETTING_KEYS.defaultAgentProvider,
    APP_SETTING_KEYS.defaultImageModel,
    APP_SETTING_KEYS.defaultImageProvider,
    APP_SETTING_KEYS.defaultSkillName,
    APP_SETTING_KEYS.defaultVideoModel,
    APP_SETTING_KEYS.defaultVideoProvider,
    APP_SETTING_KEYS.memoryUserMemoryEmbeddingModel,
    APP_SETTING_KEYS.memoryUserMemoryEmbeddingProvider,
    APP_SETTING_KEYS.memoryUserMemoryGatekeeperModel,
    APP_SETTING_KEYS.memoryUserMemoryGatekeeperProvider,
    APP_SETTING_KEYS.memoryUserMemoryLayerExtractorModel,
    APP_SETTING_KEYS.memoryUserMemoryLayerExtractorProvider,
    APP_SETTING_KEYS.memoryUserMemoryPersonaWriterModel,
    APP_SETTING_KEYS.memoryUserMemoryPersonaWriterProvider,
    APP_SETTING_KEYS.vectorEmbeddingModel,
    APP_SETTING_KEYS.vectorEmbeddingProvider,
    APP_SETTING_KEYS.vectorQueryMode,
    APP_SETTING_KEYS.vectorRerankerModel,
    APP_SETTING_KEYS.vectorRerankerProvider,
  ]),
  ...assign('storage-boolean', [
    APP_SETTING_KEYS.storageS3EnablePathStyle,
    APP_SETTING_KEYS.storageS3SetAcl,
  ]),
  ...assign('storage-file-path', [APP_SETTING_KEYS.storageS3FilePath]),
  ...assign('storage-optional-url', [
    APP_SETTING_KEYS.storageS3Endpoint,
    APP_SETTING_KEYS.storageS3PublicDomain,
  ]),
  ...assign('storage-preview-expiry-integer', [APP_SETTING_KEYS.storageS3PreviewUrlExpireIn]),
  ...assign('storage-string', [
    APP_SETTING_KEYS.storageS3AccessKeyId,
    APP_SETTING_KEYS.storageS3Bucket,
    APP_SETTING_KEYS.storageS3Region,
    APP_SETTING_KEYS.storageS3SecretAccessKey,
  ]),
  ...assign('user-global-settings-object', [APP_SETTING_KEYS.userGlobalSettingsDefaults]),
]) as Record<AppSettingKey, string>;

export const listNormalizerAdapterMismatches = (actual: Partial<Record<AppSettingKey, string>>) =>
  (Object.entries(EXPECTED_NORMALIZER_ADAPTER_BY_KEY) as Array<[AppSettingKey, string]>).flatMap(
    ([key, expected]) => (actual[key] === expected ? [] : [{ actual: actual[key], expected, key }]),
  );
