import { APP_SETTING_KEYS, type AppSettingKey } from '@/const/appSettingsRegistry';

const assign = (normalizer: string, keys: AppSettingKey[]) =>
  keys.map((key) => [key, normalizer] as const);

export const EXPECTED_NORMALIZER_BY_KEY = Object.fromEntries([
  ...assign('about', [
    APP_SETTING_KEYS.aboutLinks,
    APP_SETTING_KEYS.aboutPage,
    APP_SETTING_KEYS.helpMenuItems,
  ]),
  ...assign('boolean', [
    APP_SETTING_KEYS.authSignupEnabled,
    APP_SETTING_KEYS.authSignupPhoneEnabled,
    APP_SETTING_KEYS.composioEnabled,
    APP_SETTING_KEYS.onboardingInitialCreditsEnabled,
    APP_SETTING_KEYS.ordersManagementEnabled,
  ]),
  ...assign('bounded-integer', [
    APP_SETTING_KEYS.cronAuditRetentionDays,
    APP_SETTING_KEYS.cronPendingOrderExpiryDays,
    APP_SETTING_KEYS.onboardingInitialCredits,
    APP_SETTING_KEYS.pricingCreditMultiplier,
    APP_SETTING_KEYS.referralRewardCredits,
    APP_SETTING_KEYS.uploadMaxActualSizeMb,
    APP_SETTING_KEYS.uploadMaxInputSizeMb,
  ]),
  ...assign('brand', [
    APP_SETTING_KEYS.aboutLogoUrl,
    APP_SETTING_KEYS.brandAuthTitle,
    APP_SETTING_KEYS.brandCopyrightText,
    APP_SETTING_KEYS.brandFaviconUrl,
    APP_SETTING_KEYS.brandLoadingSvgUrl,
    APP_SETTING_KEYS.brandLoadingText,
    APP_SETTING_KEYS.brandLogoUrl,
    APP_SETTING_KEYS.brandName,
    APP_SETTING_KEYS.brandPrimaryColor,
    APP_SETTING_KEYS.brandSlogan,
    APP_SETTING_KEYS.homeMessengerEnabled,
    APP_SETTING_KEYS.homeMessengerBannerTitle,
    APP_SETTING_KEYS.sidebarGenerationLabel,
    APP_SETTING_KEYS.sidebarMemberLabel,
    APP_SETTING_KEYS.sidebarMemberUrl,
  ]),
  ...assign('desktop-login', [
    APP_SETTING_KEYS.desktopLoginCloudButtonLabel,
    APP_SETTING_KEYS.desktopLoginDescription,
    APP_SETTING_KEYS.desktopLoginFooterText,
    APP_SETTING_KEYS.desktopLoginLogoUrl,
    APP_SETTING_KEYS.desktopLoginTitle,
    APP_SETTING_KEYS.desktopLoginWindowTitle,
  ]),
  ...assign('desktop-update', [
    APP_SETTING_KEYS.desktopDownloadLabel,
    APP_SETTING_KEYS.desktopDownloadUrl,
    APP_SETTING_KEYS.desktopOssAccessKeyId,
    APP_SETTING_KEYS.desktopOssAccessKeySecret,
    APP_SETTING_KEYS.desktopOssBucket,
    APP_SETTING_KEYS.desktopOssEndpoint,
    APP_SETTING_KEYS.desktopOssPath,
    APP_SETTING_KEYS.desktopUpdateAutoCheck,
    APP_SETTING_KEYS.desktopUpdateChannel,
    APP_SETTING_KEYS.desktopUpdateCheckInterval,
    APP_SETTING_KEYS.desktopUpdateCurrentVersion,
    APP_SETTING_KEYS.desktopUpdateReleaseNotes,
    APP_SETTING_KEYS.desktopUpdateServerUrl,
  ]),
  ...assign('expert-plaza', [
    APP_SETTING_KEYS.expertPlazaCards,
    APP_SETTING_KEYS.expertPlazaCategories,
    APP_SETTING_KEYS.expertPlazaDescription,
    APP_SETTING_KEYS.expertPlazaEnabled,
    APP_SETTING_KEYS.expertPlazaName,
  ]),
  ...assign('json', [APP_SETTING_KEYS.cronSecret]),
  ...assign('model-policy', [
    APP_SETTING_KEYS.modelPolicyAllowlist,
    APP_SETTING_KEYS.modelPolicyApplyToEmbeddings,
    APP_SETTING_KEYS.modelPolicyApplyToGenerateObject,
    APP_SETTING_KEYS.modelPolicyBlocklist,
    APP_SETTING_KEYS.modelPolicyDefaultModelFallback,
    APP_SETTING_KEYS.modelPolicyDeniedMessage,
    APP_SETTING_KEYS.modelPolicyEnabled,
    APP_SETTING_KEYS.modelPolicyMode,
  ]),
  ...assign('notification', [
    APP_SETTING_KEYS.notificationDesktopEnabled,
    APP_SETTING_KEYS.notificationEmailEnabled,
    APP_SETTING_KEYS.notificationEventDefaults,
    APP_SETTING_KEYS.notificationInboxEnabled,
    APP_SETTING_KEYS.notificationPushEnabled,
    APP_SETTING_KEYS.notificationRetentionDays,
    APP_SETTING_KEYS.notificationSystemActionLabel,
    APP_SETTING_KEYS.notificationSystemActionUrl,
    APP_SETTING_KEYS.notificationSystemContent,
    APP_SETTING_KEYS.notificationSystemEnabled,
    APP_SETTING_KEYS.notificationSystemTitle,
    APP_SETTING_KEYS.notificationSystemType,
  ]),
  ...assign('object', [
    APP_SETTING_KEYS.plansFaqItems,
    APP_SETTING_KEYS.pricingModelRules,
    APP_SETTING_KEYS.userGlobalSettingsDefaults,
  ]),
  ...assign('operations', [
    APP_SETTING_KEYS.communityCreatorRewardBannerEnabled,
    APP_SETTING_KEYS.communityFeaturedAssistantPageSize,
    APP_SETTING_KEYS.communityFeaturedAssistantTitle,
    APP_SETTING_KEYS.communityFeaturedAssistantsEnabled,
    APP_SETTING_KEYS.communityFeaturedMcpPageSize,
    APP_SETTING_KEYS.communityFeaturedMcpTitle,
    APP_SETTING_KEYS.communityFeaturedMcpsEnabled,
    APP_SETTING_KEYS.communityFeaturedSkillCategory,
    APP_SETTING_KEYS.communityFeaturedSkillPageSize,
    APP_SETTING_KEYS.communityFeaturedSkillSort,
    APP_SETTING_KEYS.communityFeaturedSkillTitle,
    APP_SETTING_KEYS.communityFeaturedSkillsEnabled,
    APP_SETTING_KEYS.communityForkAndChatLabel,
    APP_SETTING_KEYS.communityHomeAnnouncementContent,
    APP_SETTING_KEYS.communityHomeAnnouncementEnabled,
    APP_SETTING_KEYS.communityHomeAnnouncementTitle,
    APP_SETTING_KEYS.communityHomeAnnouncementType,
    APP_SETTING_KEYS.communitySkillUseButtonLabel,
  ]),
  ...assign('passthrough', [
    APP_SETTING_KEYS.docmeePptAllowPdfExport,
    APP_SETTING_KEYS.docmeePptAllowPptxDownload,
    APP_SETTING_KEYS.docmeePptApiKey,
    APP_SETTING_KEYS.docmeePptAuditEnabled,
    APP_SETTING_KEYS.docmeePptBaseUrl,
    APP_SETTING_KEYS.docmeePptCreatorVersion,
    APP_SETTING_KEYS.docmeePptDailyLimit,
    APP_SETTING_KEYS.docmeePptDefaultLang,
    APP_SETTING_KEYS.docmeePptEnabled,
    APP_SETTING_KEYS.docmeePptThemeColor,
    APP_SETTING_KEYS.docmeePptTokenTtlMinutes,
  ]),
  ...assign('profile', [
    APP_SETTING_KEYS.profileAvatarPresets,
    APP_SETTING_KEYS.profileInterestAreas,
  ]),
  ...assign('recommendation', [
    APP_SETTING_KEYS.recommendationAssistantsEnabled,
    APP_SETTING_KEYS.recommendationAssistantTags,
    APP_SETTING_KEYS.recommendationAssistantTitle,
    APP_SETTING_KEYS.recommendationGeneralSkillCategories,
    APP_SETTING_KEYS.recommendationGeneralSkillsEnabled,
    APP_SETTING_KEYS.recommendationGeneralSkillTitle,
    APP_SETTING_KEYS.recommendationHotSkillsEnabled,
    APP_SETTING_KEYS.recommendationHotSkillSort,
    APP_SETTING_KEYS.recommendationHotSkillTitle,
    APP_SETTING_KEYS.recommendationMcpCategories,
    APP_SETTING_KEYS.recommendationMcpsEnabled,
    APP_SETTING_KEYS.recommendationMcpTitle,
    APP_SETTING_KEYS.recommendationSectionEnabled,
    APP_SETTING_KEYS.recommendationSelectedTags,
    APP_SETTING_KEYS.recommendationSkillCategories,
    APP_SETTING_KEYS.recommendationSkillsEnabled,
    APP_SETTING_KEYS.recommendationSkillTitle,
  ]),
  ...assign('storage', [
    APP_SETTING_KEYS.storageS3AccessKeyId,
    APP_SETTING_KEYS.storageS3Bucket,
    APP_SETTING_KEYS.storageS3EnablePathStyle,
    APP_SETTING_KEYS.storageS3Endpoint,
    APP_SETTING_KEYS.storageS3FilePath,
    APP_SETTING_KEYS.storageS3PreviewUrlExpireIn,
    APP_SETTING_KEYS.storageS3PublicDomain,
    APP_SETTING_KEYS.storageS3Region,
    APP_SETTING_KEYS.storageS3SecretAccessKey,
    APP_SETTING_KEYS.storageS3SetAcl,
  ]),
  ...assign('string', [
    APP_SETTING_KEYS.authSignupDisabledMessage,
    APP_SETTING_KEYS.composioApiKey,
    APP_SETTING_KEYS.composioAuthConfigIds,
    APP_SETTING_KEYS.defaultAgentAvatar,
    APP_SETTING_KEYS.defaultAgentModel,
    APP_SETTING_KEYS.defaultAgentName,
    APP_SETTING_KEYS.defaultAgentProvider,
    APP_SETTING_KEYS.defaultImageModel,
    APP_SETTING_KEYS.defaultImageProvider,
    APP_SETTING_KEYS.defaultSkillName,
    APP_SETTING_KEYS.defaultVideoModel,
    APP_SETTING_KEYS.defaultVideoProvider,
    APP_SETTING_KEYS.memoryUserMemoryEmbeddingModel,
    APP_SETTING_KEYS.memoryUserMemoryEmbeddingProvider,
    APP_SETTING_KEYS.memoryUserMemoryGatekeeperModel,
    APP_SETTING_KEYS.memoryUserMemoryGatekeeperProvider,
    APP_SETTING_KEYS.memoryUserMemoryLayerExtractorModel,
    APP_SETTING_KEYS.memoryUserMemoryLayerExtractorProvider,
    APP_SETTING_KEYS.memoryUserMemoryPersonaWriterModel,
    APP_SETTING_KEYS.memoryUserMemoryPersonaWriterProvider,
    APP_SETTING_KEYS.memoryUserMemoryTriggerMode,
    APP_SETTING_KEYS.vectorEmbeddingModel,
    APP_SETTING_KEYS.vectorEmbeddingProvider,
    APP_SETTING_KEYS.vectorQueryMode,
    APP_SETTING_KEYS.vectorRerankerModel,
    APP_SETTING_KEYS.vectorRerankerProvider,
  ]),
]) as Record<AppSettingKey, string>;
