#!/usr/bin/env node
/**
 * Regenerate docs/development/comhub-customization-registry.md from the
 * registry. Run after changing scripts/comhub-customizations/registry.mjs:
 *
 *   node scripts/comhub-customizations/report.mjs
 *
 * The generated doc is the machine-derived overview (per-module tables with
 * live rule paths); the human narrative history stays in
 * docs/development/comhub-upstream-customizations.md.
 */
import { execFileSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '..', '..');

const { UPSTREAM_BASELINE_TAG, registryModules } = await import(
  new URL('./registry.mjs', import.meta.url).href
);

const git = (args) =>
  execFileSync('git', args, { cwd: repoRoot, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

const parseNameStatus = (output) => {
  const files = [];
  for (const line of output.split('\n')) {
    if (!line.trim()) continue;
    const tab = line.indexOf('\t');
    if (tab < 0) continue;
    const status = line.slice(0, tab);
    let path = line.slice(tab + 1);
    if (status.startsWith('R') || status.startsWith('C')) {
      const parts = path.split('\t');
      path = parts.at(-1);
    }
    files.push({ path, status });
  }
  return files;
};

const findModuleForPath = (path) => {
  for (const module of registryModules) {
    for (const [match, ownership, note] of module.ownershipRules) {
      const hit = match.startsWith('p:')
        ? path.startsWith(match.slice(2))
        : new RegExp(match).test(path);
      if (hit) return { module, note, ownership };
    }
  }
  return null;
};

const diff = parseNameStatus(git(['diff', '--name-status', UPSTREAM_BASELINE_TAG, 'HEAD']));

const perModule = new Map();
const unregistered = [];
for (const file of diff) {
  const hit = findModuleForPath(file.path);
  if (!hit) {
    unregistered.push(file);
    continue;
  }
  if (!perModule.has(hit.module.id)) perModule.set(hit.module.id, { owned: [], upstream: [] });
  perModule.get(hit.module.id)[hit.ownership].push(file);
}

const lines = [
  '<!-- GENERATED by scripts/comhub-customizations/report.mjs — do not edit by hand. -->',
  '# ComHub Customization Registry',
  '',
  `Machine-readable registry: \`scripts/comhub-customizations/registry.mjs\` (baseline \`${UPSTREAM_BASELINE_TAG}\`).`,
  `Narrative history: \`docs/development/comhub-upstream-customizations.md\`.`,
  '',
  `PR gate: \`node scripts/comhub-customizations/verify.mjs\` — every file changed vs the baseline must be claimed by a module below.`,
  '',
  '| Module | Sync strategy | Owned files | Upstream files | Description |',
  '| --- | --- | --- | --- | --- |',
];

const moduleRows = registryModules
  .map((m) => {
    const stats = perModule.get(m.id) ?? { owned: [], upstream: [] };
    return { m, owned: stats.owned.length, upstream: stats.upstream.length };
  })
  .sort((a, b) => b.owned + b.upstream - (a.owned + a.upstream));

for (const { m, owned, upstream } of moduleRows) {
  const flag = m.plannedExtraction ? ' *(planned extraction)*' : '';
  lines.push(
    `| ${m.name} (\`${m.id}\`) | ${m.sync}${flag} | ${owned} | ${upstream} | ${m.description} |`,
  );
}
lines.push('');

for (const module of registryModules) {
  const stats = perModule.get(module.id) ?? { owned: [], upstream: [] };
  lines.push(`## ${module.name} (\`${module.id}\`)`);
  lines.push('');
  lines.push(module.description);
  if (module.plannedExtraction) {
    lines.push('');
    lines.push(
      '> **Planned extraction:** physical separation into fork-owned modules is deferred; see module notes.',
    );
  }
  lines.push('');
  lines.push(`- Sync strategy: **${module.sync}**`);
  if (module.tests.length > 0)
    lines.push(`- Tests: ${module.tests.map((t) => `\`${t}\``).join(', ')}`);
  if (module.notes) lines.push(`- Notes: ${module.notes}`);
  lines.push('');
  lines.push('| Rule | Ownership | Covers | vs baseline |');
  lines.push('| --- | --- | --- | --- |');
  for (const [match, ownership, note] of module.ownershipRules) {
    const count = ownership === 'owned' ? stats.owned.length : stats.upstream.length;
    void count; // counts are per-module, per-rule would need per-rule tallies
    lines.push(`| \`${match}\` | ${ownership} | ${note} | ${stats[ownership].length} |`);
  }
  lines.push('');
}

if (unregistered.length > 0) {
  lines.push('## Unregistered files', '');
  lines.push(
    'These changed files are NOT claimed by any module — `verify.mjs` fails until the registry claims them:',
    '',
  );
  for (const f of unregistered) lines.push(`- \`${f.path}\` (${f.status})`);
  lines.push('');
}

const outPath = resolve(repoRoot, 'docs/development/comhub-customization-registry.md');
const { writeFileSync } = await import('node:fs');
writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
console.log(
  `wrote docs/development/comhub-customization-registry.md (${registryModules.length} modules, ${diff.length} files, ${unregistered.length} unregistered)`,
);
if (unregistered.length > 0) process.exit(1);
