import { readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

describe('AuthThemeLite stylesheet setup', () => {
  it('keeps AntD component tokens generated by runtime CSS-in-JS', () => {
    const source = readFileSync(
      path.resolve(process.cwd(), 'src/app/[variants]/(auth)/_layout/AuthThemeLite.tsx'),
      'utf8',
    );

    expect(source).toContain("import 'antd/dist/reset.css';");
    expect(source).not.toContain("import 'antd/dist/antd.css';");
  });
});
